[project]
name = "mapterhorn-gdal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "mercantile>=1.2.1",
    "numpy>=2.4.4",
    "pillow>=12.2.0",
    "rasterio>=1.5.0",
    "uvicorn>=0.46.0",
]
